tunnel: cloudflared-tunnel-id
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: santa.yourdomain
    service: http://frontend:80  # or dsmr:7777, frontend:4200, etc.
  - service: http_status:404
